### ISSUE TITLE
Dockerfile for running the daemon

### ISSUE THREAD

**Issue by EpocSquadron** [cloudtools/ssh-cert-authority#5]
While it's awesome to build the project using the included Dockerfile, it would be cool to be able to build a container that has the built linux binary and can be run as an isolated server instance. This would however mean having two dockerfiles, which is a little strange I suppose. 

Thoughts?

**Comment by bobveznat** [comment]
I hadn't really thought about this until now. In looking back at the build env Dockerfile it is pretty specific to building the package and doesn't do much else. There's not much that we'd want to reuse in a runtime container. And I think that means that two dockerfiles makes sense. I'm thinking we do Dockerfile.building and Dockerfile? Imagining that the common case is someone wants to run this project, not build it.

And yay for finally having the -f flag to docker build.

I'm on a project right now where we'll want a runtime container for this service. I can take a swag at this if you haven't already done the work.

**Comment by EpocSquadron** [comment]
I started to last night but didn't get very far. If you're on it already that would be great, as I probably won't get to it today either.

**Comment by bobveznat** [comment]
I have a container built and a new Dockerfile and updated documentation.
The containers are on hub.docker.com as cloudtools/ssh-cert-authority and
cloudtools/ssh-cert-authority-buildenv.

Running it inside a container poses challenges due to the interaction with
ssh-agent. It works. And the building doc you wrote has been updated with
some hopefully helpful tips. Commit coming shortly.

**Comment by bobveznat** [comment]
I think this has been fixed for a while now? The BUILDING.rst doc has instructions.
